'use strict';
// Portable black-box acceptance: normal controls/gestures; snapshots are read only.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {chromium} = require(process.env.ECG_PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.ECG_DEMO_URL || 'http://127.0.0.1:8871';
const evidence = path.resolve(process.env.ECG_DEMO_EVIDENCE || 'build/public-demo-evidence');
fs.mkdirSync(evidence,{recursive:true});
const results = {base,started:new Date().toISOString(),checks:[],pageErrors:[],externalRequests:[],scope:'Pure mathematical browser Demo; no patient input or native database/PDF validation.'};
let browser,page;
const check = async (name,fn) => {const started=new Date().toISOString();try{const detail=await fn();results.checks.push({name,passed:true,started,detail});console.log('PASS '+name);}catch(error){results.checks.push({name,passed:false,started,error:String(error),stack:error.stack});throw error;}};
const waitReady = () => page.waitForFunction(()=>morphologyWorkbench.privateSnapshot()?.ready===true);
const snap = () => page.evaluate(()=>JSON.parse(JSON.stringify(morphologyWorkbench.privateSnapshot())));
const history = () => page.evaluate(()=>morphologyWorkbench.captureView().session.groups.history.length);
const go = async name => {await page.locator('[data-page="'+name+'"]').click();await page.waitForFunction(n=>state.currentPage===n,name);};
const ss = name => page.screenshot({path:path.join(evidence,name+'.png'),fullPage:false});
const counts = () => page.evaluate(()=>window.__CARDIOINSIGHT_MATHEMATICAL_CASE__.beats.reduce((r,b)=>(r[b.group]=(r[b.group]||0)+1,r),{}));
const apiCounts = () => page.evaluate(async()=>{const r=await fetch('/api/cases/math-4314-001/beat-editor');return (await r.json()).type_counts;});
async function chooseRange(top,bottom){const details=page.locator('.morph-keyboard-range');if(!await details.evaluate(x=>x.open))await details.locator('summary').click();for(const [id,value] of Object.entries({editRangeStart:47,editRangeEnd:54,editRangeTop:top,editRangeBottom:bottom}))await page.locator('#'+id).fill(String(value));await page.locator('#applyEditRange').click();await waitReady();return page.evaluate(()=>morphologyWorkbench.captureView().selection?.samples||[]);}
(async()=>{
 try{
  const launch={headless:true};if(process.env.ECG_CHROME)launch.executablePath=process.env.ECG_CHROME;
  browser=await chromium.launch(launch);page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(20000);
  page.on('pageerror',e=>results.pageErrors.push(String(e)));
  page.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin&&!r.url().startsWith('data:'))results.externalRequests.push(r.url());});
  await page.addInitScript(()=>{window.__demoPrintCalls=0;const nativePrint=window.print.bind(window);window.print=()=>{window.__demoPrintCalls++;return nativePrint();};window.__demoStorageReads=[];const get=Storage.prototype.getItem;Storage.prototype.getItem=function(key){window.__demoStorageReads.push(key);return get.call(this,key);};});await page.goto(base);await page.locator('#openFirstCase').click();await go('edit');await waitReady();
  let oracle,baseline,first,group6,group7,groupHistory;
  await check('mathematical source, 94-file identity and linked scope',async()=>{
   const manifest=await (await page.request.get(base+'/mathematical-source-manifest.json')).json();assert.equal(manifest.production_files_verified,94);assert.equal(manifest.production_files_modified,false);assert.equal(manifest.legacy_demo_inputs_read,false);assert.equal(manifest.mathematical_source.patient_inputs_read,false);
   oracle=await page.evaluate(()=>window.__CARDIOINSIGHT_MATHEMATICAL_CASE__.beats.filter(b=>b.group===1).map(b=>b.sample_index));first=await snap();assert.equal(first.phase,'ready');assert.deepEqual(first.sourcePopulation,oracle);const scope=await page.evaluate(()=>ECGLinkedSelection.snapshot().scope);assert.equal(scope.caseId,'math-4314-001');assert.equal(scope.beatRevision,0);assert.equal(scope.analysis_revision,0);baseline=await apiCounts();assert.equal(baseline.N,oracle.length);return {release:manifest.release_id,scope,counts:baseline};
  });
  await check('density/library immediate cards and F/Escape restore',async()=>{
   for(const [mode,button,canvas] of [['cluster','#editClusterMode','#editWaveformCanvas'],['library','#editLibraryMode','#editLibraryWaveformCanvas']]){
    await page.locator(button).click();await page.waitForFunction(m=>state.editMode===m,mode);
    const card=page.locator('#editTemplateGallery .occurrence-open').first();
    await card.waitFor();await card.click();await page.waitForFunction(()=>state.editWaveform&&state.editWaveform.start_s===state.editStart);const before=await page.evaluate(()=>({sample:state.editSelectedSample,start:state.editStart,mode:state.editMode}));assert.ok(Number.isInteger(before.sample));
    await page.locator(canvas).focus();await page.keyboard.press('f');await page.waitForFunction(()=>state.waveformExpanded===true&&Object.keys(state.waveform?.leads||{}).length===12);await ss(mode+'-12-lead');await page.keyboard.press('Escape');await page.waitForFunction(()=>state.waveformExpanded===false&&state.currentPage==='edit');const after=await page.evaluate(()=>({sample:state.editSelectedSample,start:state.editStart,mode:state.editMode}));assert.deepEqual(after,before);
   }
   await page.locator('#editClusterMode').click();await waitReady();return {modes:['cluster','library'],expandedLeads:12};
  });
  await check('template lead dialog cancel preserves local context',async()=>{const before=await snap();await page.locator('#morphLeadPicker').click();await page.waitForFunction(()=>document.querySelector('#morphLeadDialog').open&&!document.querySelector('[data-morph-lead-confirm]').disabled);await page.locator('[data-morph-lead-position="top"]').selectOption('V1');await page.locator('[data-morph-lead-cancel]').last().click();assert.deepEqual((await snap()).leads,before.leads);assert.deepEqual((await snap()).sourcePopulation,before.sourcePopulation);});
  await check('normal pointer density gate and exact selected members',async()=>{
   const canvas=page.locator('#editDensityPrimary');await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();assert.ok(box.width>0&&box.height>0);await page.mouse.move(box.x+box.width*.46,box.y+box.height*.15);await page.mouse.down();await page.mouse.move(box.x+box.width*.56,box.y+box.height*.25,{steps:8});await page.mouse.up();await page.waitForTimeout(100);await waitReady();let selected=await page.evaluate(()=>morphologyWorkbench.captureView().selection?.samples||[]);
   for(const [top,bottom] of [[6,6.5],[19.5,20],[20,20.5]]){if(selected.length>0&&selected.length<oracle.length-10)break;selected=await chooseRange(top,bottom);}
   assert.ok(selected.length>0&&selected.length<oracle.length-10,'real gate must select a nonempty proper subset');group6=selected;assert.ok(group6.every(s=>oracle.includes(s)));await page.locator('[data-group-move="6"]').click();await waitReady();assert.deepEqual((await snap()).groups[6],group6);return {population:oracle.length,selected:group6.length,pointerGeometry:box};
  });
  await check('saved group 6 and unsaved group 7 survive save/rebase/history',async()=>{
   await page.locator('#editHistogramCanvas').focus();await page.keyboard.press('Escape');await page.waitForFunction(()=>ECGLinkedSelection.snapshot().kind==='none'&&morphologyWorkbench.privateSnapshot()?.linked===null);for(const [id,val] of Object.entries({editRangeStart:0,editRangeEnd:100,editRangeTop:0,editRangeBottom:100}))await page.locator('#'+id).fill(String(val));await page.locator('#applyEditRange').click();await waitReady();group7=await page.evaluate(()=>morphologyWorkbench.captureView().selection?.samples||[]);assert.ok(group7.length>0);await page.locator('[data-group-move="7"]').click();await waitReady();await page.locator('[data-group-select="6"]').click();groupHistory=await history();assert.equal(groupHistory,2);
   await page.locator('#morphGroupTemplate').click();await page.locator('#morphTemplateName').fill('数学模板 6');await page.locator('#morphTemplateCancel').click();assert.equal(await page.locator('#morphTemplateForm').isVisible(),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'morphGroupTemplate');
   await page.locator('#morphGroupTemplate').click();await page.locator('#morphTemplateName').fill('数学模板 6');await page.locator('#morphTemplateForm button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#morphTemplateForm').hidden&&morphologyWorkbench.privateSnapshot()?.ready);const after=await snap();assert.deepEqual(after.sourcePopulation,oracle);assert.deepEqual(after.groups[6],group6);assert.deepEqual(after.groups[7],group7);assert.equal(await history(),groupHistory);assert.equal(after.analysis_revision,first.analysis_revision+1);assert.equal(after.beatRevision,0);
   const saved=await page.evaluate(async()=>{const r=await fetch('/api/cases/math-4314-001/beat-templates');return (await r.json()).items;});assert.equal(saved.length,1);assert.deepEqual(saved[0].sample_indices,group6);assert.equal(saved[0].beat_count,group6.length);assert.deepEqual(await apiCounts(),baseline);await ss('template-saved');return {saved:group6.length,unsaved:group7.length,history:groupHistory,analysisRevision:after.analysis_revision};
  });
  await check('existing template PATCH uses allowlist and cancel never writes',async()=>{await page.locator('#morphGroupTemplate').click();await page.locator('#morphTemplateName').fill('取消的数学名称');await page.locator('#morphTemplateCancel').click();await page.locator('#morphGroupTemplate').click();assert.equal(await page.locator('#morphTemplateName').inputValue(),'数学模板 6');await page.locator('#morphTemplateName').fill('数学模板 6 已编辑');await page.locator('#morphTemplateForm button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#morphTemplateForm').hidden&&morphologyWorkbench.privateSnapshot()?.ready);const item=await page.evaluate(async()=>{const r=await fetch('/api/cases/math-4314-001/beat-templates');return (await r.json()).items[0];});assert.equal(item.name,'数学模板 6 已编辑');assert.deepEqual(item.sample_indices,group6);assert.deepEqual(await apiCounts(),baseline);});
  await check('restore and undo preserve full partition and saved reference',async()=>{await page.locator('[data-group-select="7"]').click();await page.locator('#morphGroupRestore').click();await waitReady();assert.deepEqual((await snap()).groups[7],[]);await page.locator('#morphUndo').click();await waitReady();assert.deepEqual((await snap()).groups[7],group7);await page.locator('[data-group-select="6"]').click();await page.locator('#morphGroupRestore').click();await waitReady();assert.deepEqual((await snap()).groups[6],[]);await page.locator('#morphUndo').click();await waitReady();const s=await snap();assert.deepEqual(s.groups[6],group6);assert.deepEqual(s.groups[7],group7);assert.deepEqual([...s.remainder,...s.groups[6],...s.groups[7]].sort((a,b)=>a-b),oracle);const stored=await page.evaluate(async()=>{const r=await fetch('/api/cases/math-4314-001/beat-templates');return (await r.json()).items[0];});assert.equal(stored.name,'数学模板 6 已编辑');assert.deepEqual(stored.sample_indices,group6);});
  await check('adapter abort, stale basis, protected PATCH, atomic save failure/retry',async()=>{
   const result=await page.evaluate(async()=>{const url='/api/cases/math-4314-001/',get=async(p)=>{const r=await fetch(url+p);return r.json();},templates=await get('beat-templates'),item=templates.items[0],basis=await get('analysis-basis');const request=async(p,method,body)=>{const r=await fetch(p.startsWith('/api/')?p:url+p,{method,body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};const aborted=new AbortController();aborted.abort();let abortName;try{await fetch(url+'waveform',{signal:aborted.signal});}catch(e){abortName=e.name;}const stale=await request('waveform-density','POST',{revision:0,...basis,analysis_revision:basis.analysis_revision-1});const protectedPatch=await request('/api/beat-templates/'+item.id,'PATCH',{name:'invalid',sample_indices:item.sample_indices});const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='cardioinsight-public-math-4314-v2')throw new DOMException('injected storage failure','QuotaExceededError');return original.call(this,key,value);};let failure;const body={name:'数学存储重试',rhythm_family:'自定义',source_class:'source-N',lead:'II',sample_indices:item.sample_indices,revision:0};try{failure=await request('beat-templates','POST',body);}finally{Storage.prototype.setItem=original;}const afterFailure=await get('beat-templates');const retry=await request('beat-templates','POST',body);const afterRetry=await get('beat-templates');const report=await get('report'),conflict=await request('report','PUT',{status:'draft',expected_version:report.version-1,expected_review_revision:report.review_revision,conclusion:report.conclusion,composition:report.composition});return {abortName,stale:stale.status,protectedPatch:protectedPatch.status,failure:failure.status,countBefore:templates.items.length,countFailed:afterFailure.items.length,retry:retry.status,countRetry:afterRetry.items.length,conflict:conflict.status};});assert.equal(result.abortName,'AbortError');assert.equal(result.stale,409);assert.equal(result.protectedPatch,400);assert.equal(result.failure,400);assert.equal(result.countFailed,result.countBefore);assert.equal(result.retry,201);assert.equal(result.countRetry,result.countBefore+1);assert.equal(result.conflict,409);return result;
  });
  await go('stt');await page.waitForFunction(()=>state.sttWaveform&&document.querySelector('#saveSttAnnotation').disabled===false);
  await check('ST lead update retains draft, measurements and cached review',async()=>{await page.locator('#sttReviewNote').fill('纯数学 browser-only 复核');await page.locator('#sttSignalChecked').check();const before=await page.evaluate(()=>({review:state.sttReview,landmarks:{iso:state.sttIsoFraction,j:state.sttJFraction},measurement:state.sttMeasurementMs,start:state.sttStart,duration:state.sttDuration}));await page.evaluate(()=>{window.__demoStReview=state.sttReview;});await page.locator('#sttLeadPickerButton').click();await page.locator('[data-stt-lead-choice][value="II"]').locator('..').click();assert.equal(await page.locator('[data-stt-lead-choice][value="II"]').isChecked(),false);await page.locator('[data-stt-lead-choice][value="I"]').locator('..').click();assert.equal(await page.locator('[data-stt-lead-choice][value="I"]').isChecked(),true);await page.locator('#applySttLeadSelection').click();await page.waitForFunction(()=>state.sttWaveform?.leads?.I&&document.querySelector('#saveSttAnnotation').disabled===false);assert.equal(await page.locator('#sttReviewNote').inputValue(),'纯数学 browser-only 复核');assert.equal(await page.locator('#sttSignalChecked').isChecked(),true);const after=await page.evaluate(()=>({review:state.sttReview,landmarks:{iso:state.sttIsoFraction,j:state.sttJFraction},measurement:state.sttMeasurementMs,start:state.sttStart,duration:state.sttDuration}));assert.deepEqual(after,before);assert.equal(await page.evaluate(()=>state.sttReview===window.__demoStReview),true);await ss('st-local');});
  await check('ST explicit manual save remains browser-only and counts stable',async()=>{await page.locator('#saveSttAnnotation').click();await page.waitForFunction(()=>!state.sttSaving&&document.querySelector('#sttReviewNote').value===''&&state.sttWaveform);const annotations=await page.evaluate(async()=>{const r=await fetch('/api/cases/math-4314-001/annotations');return (await r.json()).items;});assert.ok(annotations.some(a=>a.note.includes('纯数学 browser-only 复核')));assert.deepEqual(await apiCounts(),baseline);return {annotations:annotations.length};});
  await go('report');await page.waitForFunction(()=>!state.reportEvidenceLoading&&!state.reportEvidenceError&&!state.reportViewLoading&&!state.reportViewError);
  await check('report category updates are local and counts remain stable',async()=>{await page.evaluate(()=>{window.__demoReportCounts=JSON.stringify(state.caseData.calculated.group_counts);window.__demoConclusionNode=document.querySelector('#conclusionEditor');});await page.locator('[data-category="V"]').click();await page.waitForFunction(()=>state.reportDisplayedCategory==='V'&&!state.reportViewLoading);assert.equal(await page.evaluate(()=>document.querySelector('#conclusionEditor')===window.__demoConclusionNode),true);assert.equal(await page.evaluate(()=>JSON.stringify(state.caseData.calculated.group_counts)===window.__demoReportCounts),true);assert.deepEqual(await apiCounts(),baseline);const buttons=await page.locator('#reportV2Content button').evaluateAll(xs=>xs.map(e=>({text:e.textContent.trim(),data:e.dataset})));return {buttons};});
  await check('report pending range blocks save, explicit discard, apply persists and reopens',async()=>{
   await page.locator('[data-locate]').first().click();await page.locator('[data-range-drag="start"]').waitFor();const range=page.locator('[data-range-drag="start"]');await range.focus();await page.keyboard.press('Shift+ArrowRight');await page.waitForFunction(()=>ECGReportRange.pending().length===1);const pending=await page.evaluate(()=>({a:ECGReportRange.pending()[0].a,b:ECGReportRange.pending()[0].b}));const before=await page.evaluate(()=>state.report.version);await page.locator('#saveReport').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>state.report.version),before);assert.equal(await page.evaluate(()=>ECGReportRange.pending().length),1);await page.locator('[data-range-discard]').click();await page.locator('[data-range-confirm-discard]').click();await page.waitForFunction(()=>ECGReportRange.pending().length===0);assert.equal(await page.evaluate(()=>state.reportComposition.selected_events?.length||0),0);await page.locator('[data-range-drag="start"]').focus();await page.keyboard.press('Shift+ArrowRight');await page.waitForFunction(()=>ECGReportRange.pending().length===1);assert.deepEqual(await page.evaluate(()=>({a:ECGReportRange.pending()[0].a,b:ECGReportRange.pending()[0].b})),pending);await page.locator('[data-range-apply]').click();await page.waitForFunction(()=>ECGReportRange.pending().length===0&&state.reportComposition.selected_events?.length>0);const selected=await page.evaluate(()=>state.reportComposition.selected_events);assert.equal(selected[0].range_start_s,pending.a);assert.equal(selected[0].range_end_s,pending.b);await page.locator('[data-category="final"]').click();await page.waitForFunction(()=>state.reportDisplayedCategory==='final'&&!state.reportViewLoading);await page.locator('#conclusionEditor').fill('数学交互演示草稿，不用于临床判读。');await page.locator('#saveReport').click();await page.waitForFunction(()=>!state.reportSaving&&!state.reportDirty);const saved=await page.evaluate(()=>state.report);assert.equal(saved.conclusion,'数学交互演示草稿，不用于临床判读。');assert.deepEqual(saved.composition.selected_events,selected);await ss('report-applied');await page.reload();await page.locator('#openFirstCase').click();await go('report');await page.waitForFunction(()=>!state.reportEvidenceLoading&&!state.reportViewLoading&&state.report?.conclusion==='数学交互演示草稿，不用于临床判读。');assert.deepEqual(await page.evaluate(()=>state.report.composition.selected_events),selected);const templates=await page.evaluate(async()=>{const r=await fetch('/api/cases/math-4314-001/beat-templates');return (await r.json()).items;});assert.equal(templates.length,2);assert.deepEqual(templates.find(x=>x.name==='数学模板 6 已编辑').sample_indices,group6);return {range:pending,version:saved.version,selectedEvents:selected.length};
  });
  await go('edit');await waitReady();
  await check('N/S/V filters use full counts and template reopens without reclassification',async()=>{const detail={};for(const code of ['N','S','V']){await page.locator('#editType'+code).click();await page.locator('#editTypeMenu [data-code="'+code+'"][data-mode="all"][data-template="all"]').click();await page.waitForFunction(c=>state.editSelectedClass==='source-'+c&&morphologyWorkbench.privateSnapshot()?.ready,code);const s=await snap();assert.equal(s.sourcePopulation.length,baseline[code]);assert.equal(s.source, 'source-'+code);detail[code]=s.sourcePopulation.length;}await page.locator('#editTypeN').click();await page.locator('#editTypeMenu [data-code="N"][data-mode="all"][data-template="all"]').click();await waitReady();await page.locator('#occSearch').fill('数学模板 6 已编辑');const opts=await page.locator('#occTemplate option').evaluateAll(xs=>xs.map(e=>({text:e.textContent,value:e.value})));const savedOption=opts.find(x=>x.text.includes('数学模板 6 已编辑'));assert.ok(savedOption);await page.locator('#occTemplate').selectOption(savedOption.value);await page.waitForFunction(()=>morphologyWorkbench.privateSnapshot()?.ready&&morphologyWorkbench.privateSnapshot().source.startsWith('custom-'));assert.deepEqual((await snap()).sourcePopulation,group6);assert.deepEqual(await apiCounts(),baseline);return detail;});
  await go('trends');await page.locator('#hrvWindowPanel .hrv-continuous-analysis').waitFor();
  await check('HRV continuous sections precede expandable A4 preview',async()=>{const shape=await page.locator('#hrvWindowPanel .hrv-evidence-workspace').evaluate(host=>{const continuous=host.querySelector('.hrv-continuous'),paper=host.querySelector('.hrv-paper-preview');return {analysis:continuous.querySelectorAll('.hrv-continuous-analysis').length,trends:continuous.querySelectorAll('.hrv-continuous-trends').length,paperAfter:!!(continuous.compareDocumentPosition(paper)&Node.DOCUMENT_POSITION_FOLLOWING),open:paper.open,paperPages:paper.querySelectorAll('.rp-sheet').length};});assert.equal(shape.analysis,1);assert.equal(shape.trends,1);assert.equal(shape.paperAfter,true);assert.equal(shape.open,false);assert.ok(shape.paperPages>=2);await page.locator('#hrvWindowPanel .hrv-paper-preview summary').click();assert.equal(await page.locator('#hrvWindowPanel .hrv-paper-preview').evaluate(e=>e.open),true);await ss('hrv-a4-tail');assert.deepEqual(await apiCounts(),baseline);return shape;});
  await check('HRV browser printing entry creates numbered A4 sheets',async()=>{const before=await page.evaluate(()=>state.report.version);await page.locator('#hrvWindowPanel [data-hrv-export]').click();await page.waitForFunction(()=>document.querySelector('#v2PrintFrame')?.contentWindow.__demoPrintCalls===1);const printed=await page.locator('#v2PrintFrame').evaluate(frame=>({title:frame.contentDocument.title,printCalls:frame.contentWindow.__demoPrintCalls,pages:frame.contentDocument.querySelectorAll('.rp-sheet').length,numbers:[...frame.contentDocument.querySelectorAll('[data-rp-page]')].map(e=>e.textContent),a4:[...frame.contentDocument.styleSheets].some(sheet=>[...sheet.cssRules].some(rule=>/\bsize:\s*a4\b/i.test(rule.cssText)))}));results.printAttempt=printed;assert.equal(printed.printCalls,1);assert.ok(printed.pages>=2);assert.equal(printed.a4,true);assert.ok(printed.numbers.every(Boolean));assert.equal(await page.evaluate(()=>state.report.version),before);return {...printed,validation:'Headless browser print() invocation and A4 HTML only; native PDF bytes and OS print dialog were not tested.'};});
  await check('no browser errors or external dataset requests',async()=>{assert.deepEqual(results.pageErrors,[]);assert.deepEqual(results.externalRequests,[]);const keys=await page.evaluate(()=>[...new Set(window.__demoStorageReads)]);assert.ok(keys.length>0);assert.ok(keys.every(k=>k.startsWith('cardioinsight-public-math-4314-v2')),JSON.stringify(keys));return {storageReadKeys:keys};});
 }catch(error){results.failure=String(error);if(page)await page.screenshot({path:path.join(evidence,'failure.png'),fullPage:false}).catch(()=>{});process.exitCode=1;console.error(error.stack);}
 finally{if(browser)await browser.close();results.finished=new Date().toISOString();results.browserClosed=true;fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify(results,null,2)+'\n');}
})();
